%% Computing and using an AcousticGreenFunction1D
% This example computes the pressure Green's function generated by one
% pressure monopole and sampled at three receiver locations. It then creates
% a ConvMultiOp and applies the operator to a new source time function.

clear
close all

%% Physical domain, medium, and PML
domain = [0,1];
medium = AcousticMedium1D.constant(KappaValue=1,BetaValue=1);
pml = PML1D(WidthLeft=0.2,WidthRight=0.2);

%% Computational and output spatial grids
% The output grid contains the receiver points. A single GreenFunction may
% have many output channels, but it corresponds to only one multipole
% component and hence one input channel.

Nx = 201;
primal = Grid1DUnifPrimal(domain,Nx);
computationalGrid = GridSpace1D(primal);

receiverLocations = [0.2,0.5,0.8];
outputGrid = GridSpace1D( ...
    Grid1DUnifPrimal([receiverLocations(1),receiverLocations(end)], ...
    numel(receiverLocations)));

%% Uniform convolution time grid
% The time step is chosen from the fourth-order spatial CFL restriction.
% GreenFunction stores K input/output times and 2*K-1 time lags.

[~,~,~,cMax] = sampleMedium1D(computationalGrid,medium);
T = 1;
dtEstimate = 0.8*(6/7)*computationalGrid.h/cMax;
K = ceil(T/dtEstimate)+1;
times = linspace(0,T,K);

%% Configure the acoustic solver
% The solver is constructed outside GreenFunction. It owns the medium, PML,
% spatial grids, complete solver time grid, and numerical options. The extra
% time level -dt is required by the discrete impulse and leapfrog scheme.

solverTimes = [-times(2),times];
solver = AcousticSolver1D_PML( ...
    computationalGrid,solverTimes,outputGrid,solverTimes,medium,pml, ...
    SpatialOrder=4);

%% Define and compute the Green function
% The component identifies the spatial source and the acoustic equation into
% which it is injected. OutputField identifies the field recorded at the
% receiver grid. GreenFunction receives the configured solver by dependency
% injection, so it is not coupled to AcousticSolver1D_PML internally.

component = MultipoleComponent1D( ...
    0.4,0,TargetField="pressure");

G = AcousticGreenFunction1D( ...
    component,solver,OutputField="pressure");

G.compute(4);

fprintf('Stored kernel size: %d-by-%d\n',size(G.values))
fprintf('Zero-lag index: %d\n',G.zeroLagIndex)

%% Plot the receiver kernels
figure
plot(G.lags,G.values,'LineWidth',1.2)
xline(0,':k')
xlabel('Time lag')
ylabel('Pressure Green function')
legend(compose('x_r = %.1f',receiverLocations),Location='best')
title('Green functions at the receiver locations')
grid on

%% Generate the linear operator
% makeLinearOp returns a one-input, three-output ConvMultiOp. The Green
% values are stored without scaling; the operator supplies the dt factor.

A = G.makeLinearOp();
fprintf('Operator dimensions: %d-by-%d\n',A.dimRange,A.dimDomain)

%% Apply the operator to a new time function
w = exp(-((times(:)-0.35)/0.08).^2);
d = A.fwd(w);
D = reshape(d,G.numberOfTimes,G.numberOfOutputChannels);

figure
tiledlayout(2,1)
nexttile
plot(times,w,'LineWidth',1.2)
xlabel('Time')
title('Source time function')
grid on

nexttile
plot(times,D,'LineWidth',1.2)
xlabel('Time')
ylabel('Pressure')
legend(compose('x_r = %.1f',receiverLocations),Location='best')
title('Pressure data generated by convolution')
grid on

%% Check the adjoint identity
% rng(3)
% y = randn(A.dimRange,1);
% lhs = dot(A.fwd(w),y);
% rhs = dot(w,A.adj(y));
% relativeAdjointError = abs(lhs-rhs)/max([1,abs(lhs),abs(rhs)]);
% fprintf('Relative adjoint error: %.3e\n',relativeAdjointError)
